### PR TITLE
Rebase saxon branch on top of v2020.07

### PR DESCRIPTION
**Pull request by roman3017**
@Dolu1990 I have rebased saxon branch on top of official v2020.07 released today. I have fixed some compilation errors and it works fine for me.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks :D

**Comment by Dolu1990** [comment]
Got a 

```
Error: You must add new CONFIG options using Kconfig
The following new ad-hoc CONFIG options were detected:
CONFIG_SBI_V01
```

What is it ?

**Comment by Dolu1990** [comment]
hmm
you were not working in the smp branch ?

**Comment by Dolu1990** [comment]
( i reverted the merge ), will have to open a new pull request XD

**Comment by roman3017** [comment]
I can open a new PR. Just wonder when did you get:
```
Error: You must add new CONFIG options using Kconfig
The following new ad-hoc CONFIG options were detected:
CONFIG_SBI_V01
```
I was merging branch saxon to saxon, which should work for both smp and non-smp configurations.

**Comment by roman3017** [comment]
I can reproduce it now. Need to update arch/riscv/Kconfig. Will fix it in new PR.

Edit: It is fixed now.

**Comment by Dolu1990** [comment]
How is it possible that we have to update arch/riscv/Kconfig ?
I mean, seem to me that it mean getting away from mainline isn't it ?

**Comment by roman3017** [comment]
@Dolu1990  There are additional three commits I had to cherry pick from smp branch to have sbi and smp working.

Those commits are already accepted to uboot. I can see them here:
[upstream patches](https://patchwork.ozlabs.org/project/uboot/list/?submitter=64981&state=*)
https://patchwork.ozlabs.org/project/uboot/patch/1586353273-12255-5-git-send-email-bmeng.cn@gmail.com/
https://patchwork.ozlabs.org/project/uboot/patch/1586353273-12255-3-git-send-email-bmeng.cn@gmail.com/

Alternatively, we can wait for next RC, which should have these changes and rebase then.

**Comment by Dolu1990** [comment]
@roman3017 hmm basicaly, the smp and the saxon branch shouldn't be cherry picked between each others, but instead the smp branch should be merged back into the saxon branch. The goal insn't to keep the smp branch alive for long :)


About the u-boot updates, are those patches necessary ? why not just updating to mainline ?

**Comment by Dolu1990** [comment]
to be clearer about the branch management, currently, the head of this repo for dev is the smp branch, which will be merged back into the sxon branch at terms :)

**Comment by roman3017** [comment]
I thought this rebased branch is clean and it provides the same functionality as smp and saxon branches. Three additional patches will be available in the next release and hence they are not moving away from upstream code. If you check it out from my repo and look at its history it has official v2020.07 release and few saxon related patches on top of it.

I thought that regularly rebasing on top of the latest release would make upstreaming easier later. One can see what needs to be upstreamed, since all patches are on top of the official release. But you may have a different plan on your mind.

If I just updated to mainline without those three future patches smp, sbi and sbi uart would not compile. One gets CONFIG_SBI_V01 error you have noticed first and I have seen it after mrproper clean and recompile. With the three future patches it seems all works fine and one can use this uboot with smp version of saxon too.

If you would prefer to stay on the current release for now it is fine too and I can cancel the pull request.

**Comment by Dolu1990** [comment]
> I thought this rebased branch is clean and it provides the same functionality as smp and saxon branches. Three additional patches will be available in the next release and hence they are not moving away from upstream code. If you check it out from my repo and look at its history it has official v2020.07 release and few saxon related patches on top of it.

If that's 100 % sure to be in the next release, that's ok. Basicaly i'm just realy trying to avoid branching off mainline, as it could result into painefull and riscky merge busy work.

> I thought that regularly rebasing on top of the latest release would make upstreaming easier later. One can see what needs to be upstreamed, since all patches are on top of the official release. But you may have a different plan on your mind.

Hmm that's a double edged sword, i agree that it's good to keep up with upstream, but on the other end, it cost manpower to test things again, and also, there is the risk of breaking stuff / having new hidden bugs. Personnaly, when i have something working and stable, if there is no missing feature, i just let it in that state (again, manpower is limited, and i try to reduce risks)

> If you would prefer to stay on the current release for now it is fine too and I can cancel the pull request.

I'm fine with the PR, but please, in the smp branch, not in the saxon branch. Saxon branch is used by others for SoCs that we do not do active dev/test on, so i don't want to break things there yet.

Is that fine ? PR for the smp branch ?

**Comment by roman3017** [comment]
I agree that with every change there is a possibility to break something. I will cancel PR for saxon and will have a look if smp can be easily rebased on top of v2020.07 instead.

Edit: Looking at smp history, it has some commits repeated.
```
$ git log --author roman3017 --oneline

856c7b831a (HEAD -> smp, github/smp) Add Spinal MAC driver
0c70b08523 Saxon SPL related changes
774a5e4d4f Saxon SPL related changes
32468c2d44 Remove unused serial_vexriscv driver
de6e7a309a Merge pull request #6 from kost/ulx3s-auto-part-fat
57109d5dd6 Add Saxon support for Lichee Tang board
13000d6edb Fix spi-max-frequency in nexysa7 device tree
0762fe93c4 Merge pull request #5 from roman3017/saxon
cb5fb57bd2 Disable SPL which does not work yet
7bad3dc94f Merge branch 'saxon' into saxon

<- REPEATING COMMITS END

b21552b3eb Fix memory banksize when OF_CONTROL is disabled
4bca41e935 Fix vexriscv_spi when OF_CONTROL is disabled
490271464f Add NexysA7 support
998c3be238 Saxon: SPL changes for  mmc_spi and clean up
6b33ca6345 Saxon: Remove failing aliases and adding SPL definitions
48bf9495cb Saxon: Increase spi-max-frequency in mmc-spi
c6e5caf5c2 Revert "MMC: Disable CMD10 and CMD9 when defined MMC_SPI"
06a65159bf Enable MMC_SPI_CRC_ON
faf21194dc MMC: Disable CMD10 and CMD9 when defined MMC_SPI
a772aaaed0 Add Saxon SPI driver
e04345ad54 Fix SPL DM when FDT is disabled
b8033160f6 Add Saxon SPL support
f945ec8966 Enable MMC in Saxon defconfig
74d666b6ec Add vexriscv saxon support

<- REPEATING COMMITS START

efeedc347a Fix memory banksize when OF_CONTROL is disabled
b22806a551 Fix vexriscv_spi when OF_CONTROL is disabled
b961faf55d Merge pull request #3 from roman3017/saxon
a3fb2e1422 Add NexysA7 support
a5ec00769f Merge pull request #2 from roman3017/saxon
240537fa6a Saxon: SPL changes for  mmc_spi and clean up
4f40a8a63b Merge pull request #1 from roman3017/saxon
81562aab53 Saxon: Remove failing aliases and adding SPL definitions
5920160f55 Saxon: Increase spi-max-frequency in mmc-spi
487b9c596c Revert "MMC: Disable CMD10 and CMD9 when defined MMC_SPI"
b105b37def Enable MMC_SPI_CRC_ON
7c1479fdeb MMC: Disable CMD10 and CMD9 when defined MMC_SPI
734080c5bc Add Saxon SPI driver
8e8818e29f Fix SPL DM when FDT is disabled
69d6b1b8b2 Add Saxon SPL support
f0e74aa3c6 Enable MMC in Saxon defconfig
16ed01b300 Add vexriscv saxon support
```

Edit: Now I see same issue with saxon branch. Will try to fix it:

```
$ git log --author roman3017 --oneline

09844a805d (HEAD -> saxon, spinal/saxon) Saxon fix SYS_MALLOC_F_LEN
62172c1df1 Remove conflicting riscv_cpu UCLASS_DRIVER
5383a42f1c Saxon SPL fix text base address
573bfdc065 Refactor saxon_nexysa7 into saxon_nexys_a7
78c6f99362 Saxon SPL change memory layout
b54ae0ebd1 Saxon SPL related changes
a558972946 Saxon SPL related changes
1b9f50efd0 Remove unused serial_vexriscv driver
d318f077fb Fix ofnode_read_u32_default
bb86e53beb Merge pull request #6 from kost/ulx3s-auto-part-fat
8ab6c9505f Add Saxon support for Lichee Tang board
1b10e5f2a5 Fix spi-max-frequency in nexysa7 device tree
6c08f2363e Merge pull request #5 from roman3017/saxon
9b627585ea Disable SPL which does not work yet
a5c948f173 Merge branch 'saxon' into saxon

a487fe07a5 Fix memory banksize when OF_CONTROL is disabled
ad3d48ec40 Fix vexriscv_spi when OF_CONTROL is disabled
4db277ee8f Add NexysA7 support
db5af01785 Saxon: SPL changes for  mmc_spi and clean up
7dcf2b58d4 Saxon: Remove failing aliases and adding SPL definitions
8ca01f2b1a Saxon: Increase spi-max-frequency in mmc-spi
26e57733e8 Revert "MMC: Disable CMD10 and CMD9 when defined MMC_SPI"
cd22409631 Enable MMC_SPI_CRC_ON
2a212784c1 MMC: Disable CMD10 and CMD9 when defined MMC_SPI
0c52b5fb81 Add Saxon SPI driver
43875224ef Fix SPL DM when FDT is disabled
fd1e3b3fa7 Add Saxon SPL support
2a070321fb Enable MMC in Saxon defconfig
60ce1ead1a Add vexriscv saxon support

efeedc347a Fix memory banksize when OF_CONTROL is disabled
b22806a551 Fix vexriscv_spi when OF_CONTROL is disabled
b961faf55d Merge pull request #3 from roman3017/saxon
a3fb2e1422 Add NexysA7 support
a5ec00769f Merge pull request #2 from roman3017/saxon
240537fa6a Saxon: SPL changes for  mmc_spi and clean up
4f40a8a63b Merge pull request #1 from roman3017/saxon
81562aab53 Saxon: Remove failing aliases and adding SPL definitions
5920160f55 Saxon: Increase spi-max-frequency in mmc-spi
487b9c596c Revert "MMC: Disable CMD10 and CMD9 when defined MMC_SPI"
b105b37def Enable MMC_SPI_CRC_ON
7c1479fdeb MMC: Disable CMD10 and CMD9 when defined MMC_SPI
734080c5bc Add Saxon SPI driver
8e8818e29f Fix SPL DM when FDT is disabled
69d6b1b8b2 Add Saxon SPL support
f0e74aa3c6 Enable MMC in Saxon defconfig
16ed01b300 Add vexriscv saxon support
```

**Comment by roman3017** [comment]
I think the problem we experience here is the same as this one:
https://github.community/t/merge-conflicts-on-github-not-locally/949/9

After rebasing and creating PR there is always a small conflict in Github (not locally). When it is resolved, Github creates "Merge branch 'saxon' into saxon" which repeats commits. This happened already when rebasing to v2020.01.

The easiest would be to force push rebased repo without PR. We can start with smp branch, which is fixed in my repo. Fixed saxon branch is called vexriscv in my repo.

**Comment by Dolu1990** [comment]
Ok for me to force push :)

**Comment by roman3017** [comment]
@Dolu1990 Thanks, I have force pushed smp branch. Please let me know if you see any issues.

**Pull request merged**
